export const geometryArguments: { [k: string]: string[] } = {
  box: ['width', 'height', 'depth', 'widthSegments', 'heightSegments', 'depthSegments'],
  capsule: ['radius', 'length', 'capSubdivisions', 'radialSegments'],
  circle: ['radius', 'segments', 'thetaStart', 'thetaLength'],
  cone: ['radius', 'height', 'radialSegments', 'heightSegments', 'openEnded', 'thetaStart', 'thetaLength'],
  cylinder: ['radiusTop', 'radiusBottom', 'height', 'radialSegments', 'heightSegments', 'openEnded', 'thetaStart', 'thetaLength'],
  dodecahedron: ['radius', 'detail'],
  // extrude: ['shape', 'options'],
  icosahedron: ['radius', 'detail'],
  // lathe: ['points', 'segments', 'phiStart', 'phiLength'],
  octahedron: ['radius', 'detail'],
  parametric: ['func', 'slices', 'stacks'],
  plane: ['width', 'height', 'widthSegments', 'heightSegments'],
  polyhedron: ['vertices', 'indices', 'radius', 'detail'],
  ring: ['innerRadius', 'outerRadius', 'thetaSegments', 'phiSegments', 'thetaStart', 'thetaLength'],
  // shape: ['shape', 'options'],
  sphere: ['radius', 'widthSegments', 'heightSegments', 'phiStart', 'phiLength', 'thetaStart', 'thetaLength'],
  tetrahedron: ['radius', 'detail'],
  text: ['text', 'parameters'],
  torus: ['radius', 'tube', 'radialSegments', 'tubularSegments', 'arc'],
  torusKnot: ['radius', 'tube', 'tubularSegments', 'radialSegments', 'p', 'q'],
  tube: ['path', 'tubularSegments', 'radius', 'radiusSegments', 'closed'],
};
